export enum PostType {
  TEXT = 'TEXT',
  ACHIEVEMENT = 'ACHIEVEMENT',
  CHALLENGE_CREATED = 'CHALLENGE_CREATED',
  CHALLENGE_ON_TRACK = 'CHALLENGE_ON_TRACK',
  CHALLENGE_COMPLETED = 'CHALLENGE_COMPLETED',
  IMAGE = 'IMAGE',
}

export enum PostVisibility {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}

export enum ChallengeStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export class PostEntity {
  id!: string;
  userId!: string;
  groupId!: string | null;
  challengeId!: string | null;
  content!: string | null;
  type!: PostType;
  mediaUrl!: string | null;
  visibility!: PostVisibility;
  isAutoGenerated!: boolean;
  challengeTitle!: string | null;
  taggedUserIds!: string[];
  hashtags!: string[];
  commentCount!: number;
  likeCount?: number;
  createdAt!: Date;
  updatedAt!: Date;

  constructor(partial: Partial<PostEntity>) {
    Object.assign(this, partial);
  }
}

export class CommentEntity {
  id!: string;
  postId!: string;
  userId!: string;
  content!: string;
  createdAt!: Date;

  constructor(partial: Partial<CommentEntity>) {
    Object.assign(this, partial);
  }
}

export class ChallengeEntity {
  id!: string;
  groupId!: string;
  creatorId!: string;
  title!: string;
  description!: string | null;
  status!: ChallengeStatus;
  imageUrl!: string | null;
  startDate!: Date;
  endDate!: Date | null;
  memberCount?: number;

  constructor(partial: Partial<ChallengeEntity>) {
    Object.assign(this, partial);
  }
}

export class GroupEntity {
  id!: string;
  name!: string;
  description!: string | null;
  coverImageUrl!: string | null;
  profileImageUrl!: string | null;
  isPublic!: boolean;
  memberCount?: number;
  createdAt!: Date;

  constructor(partial: Partial<GroupEntity>) {
    Object.assign(this, partial);
  }
}
