import { Inject, Injectable } from '@nestjs/common';
import type { IUseCase } from '../../../shared/domain/ports/use-case.port';
import { IPostRepository } from '../domain/repositories/post.repository.interface';
import { IFollowLocalDataSource } from '../../profile/infrastructure/data-sources/follow.local.datasource.interface';
import { PostEntity } from '../domain/entities/community.entity';
import type { CreatePostDto } from './dtos/create-post.dto';

@Injectable()
export class CreatePostUseCase implements IUseCase<PostEntity, CreatePostDto> {
  constructor(
    @Inject(IPostRepository)
    private readonly postRepository: IPostRepository,
    @Inject(IFollowLocalDataSource)
    private readonly followLocalDataSource: IFollowLocalDataSource,
  ) {}

  async execute(params: CreatePostDto): Promise<PostEntity> {
    const postData: Partial<PostEntity> = {
      userId: params.userId,
      groupId: params.groupId || null,
      challengeId: params.challengeId || null,
      content: params.content || null,
      type: params.type,
      mediaUrl: params.mediaUrl || null,
      visibility: params.visibility,
      isAutoGenerated: false,
      taggedUserIds: params.taggedUserIds || [],
      hashtags: params.hashtags || [],
    };

    const created = await this.postRepository.create(postData);
    try {
      await this.followLocalDataSource.addPostToFollowersFeeds(
        created.userId,
        created.id,
        created.createdAt,
      );
    } catch {
      // Redis fan-out failure; post is created, feed may be eventually consistent
    }
    return created;
  }
}
