import { Inject, Injectable } from '@nestjs/common';
import { IPostRepository } from '../domain/repositories/post.repository.interface';
import { PostEntity, PostType, PostVisibility } from '../domain/entities/community.entity';

export interface CreatePostDto {
  userId: string;
  groupId?: string;
  challengeId?: string;
  content?: string;
  type: PostType;
  mediaUrl?: string;
  visibility: PostVisibility;
  taggedUserIds?: string[];
  hashtags?: string[];
}

@Injectable()
export class CreatePostUseCase {
  constructor(
    @Inject(IPostRepository)
    private readonly postRepository: IPostRepository,
  ) {}

  async execute(dto: CreatePostDto): Promise<PostEntity> {
    const postData: Partial<PostEntity> = {
      userId: dto.userId,
      groupId: dto.groupId || null,
      challengeId: dto.challengeId || null,
      content: dto.content || null,
      type: dto.type,
      mediaUrl: dto.mediaUrl || null,
      visibility: dto.visibility,
      isAutoGenerated: false,
      taggedUserIds: dto.taggedUserIds || [],
      hashtags: dto.hashtags || [],
    };

    return this.postRepository.create(postData);
  }
}
