/*
  Warnings:

  - You are about to drop the column `imageUrl` on the `post` table. All the data in the column will be lost.
  - Added the required column `creatorId` to the `challenge` table without a default value. This is not possible if the table is not empty.
  - Added the required column `updatedAt` to the `group` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "habitracker_app"."PostType" AS ENUM ('TEXT', 'ACHIEVEMENT', 'CHALLENGE_CREATED', 'CHALLENGE_ON_TRACK', 'CHALLENGE_COMPLETED', 'IMAGE');

-- CreateEnum
CREATE TYPE "habitracker_app"."PostVisibility" AS ENUM ('PUBLIC', 'PRIVATE');

-- CreateEnum
CREATE TYPE "habitracker_app"."ChallengeStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'CANCELLED');

-- DropForeignKey
ALTER TABLE "habitracker_app"."challenge_member" DROP CONSTRAINT "challenge_member_challengeId_fkey";

-- DropForeignKey
ALTER TABLE "habitracker_app"."challenge_member" DROP CONSTRAINT "challenge_member_userId_fkey";

-- AlterTable
ALTER TABLE "auth"."user" ALTER COLUMN "originAppId" SET DEFAULT 'habitracker';

-- AlterTable
ALTER TABLE "habitracker_app"."category" ADD COLUMN     "imageUrl" TEXT,
ADD COLUMN     "isPredefined" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "userId" TEXT;

-- AlterTable
ALTER TABLE "habitracker_app"."challenge" ADD COLUMN     "autoCreateTaskOnJoin" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "autoPostOnCompletion" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "autoPostOnProgress" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "creatorId" TEXT NOT NULL,
ADD COLUMN     "imageUrl" TEXT,
ADD COLUMN     "onTrackStreakThreshold" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "status" "habitracker_app"."ChallengeStatus" NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN     "taskTemplate" JSONB;

-- AlterTable
ALTER TABLE "habitracker_app"."group" ADD COLUMN     "allowMemberInvites" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "coverImageUrl" TEXT,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "isPublic" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "profileImageUrl" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL,
ADD COLUMN     "updatedBy" TEXT;

-- AlterTable
ALTER TABLE "habitracker_app"."habit_profile" ADD COLUMN     "isTaggingAllowed" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "habitracker_app"."post" DROP COLUMN "imageUrl",
ADD COLUMN     "challengeId" TEXT,
ADD COLUMN     "challengeTitle" TEXT,
ADD COLUMN     "commentCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "groupId" TEXT,
ADD COLUMN     "hashtags" TEXT[],
ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "mediaUrl" TEXT,
ADD COLUMN     "pendingTagUserIds" TEXT[],
ADD COLUMN     "rejectedTagUserIds" TEXT[],
ADD COLUMN     "taggedUserIds" TEXT[],
ADD COLUMN     "type" "habitracker_app"."PostType" NOT NULL DEFAULT 'TEXT',
ADD COLUMN     "visibility" "habitracker_app"."PostVisibility" NOT NULL DEFAULT 'PUBLIC';

-- AlterTable
ALTER TABLE "habitracker_app"."task" ADD COLUMN     "challengeId" TEXT;

-- AlterTable
ALTER TABLE "habitracker_app"."task_completion" ADD COLUMN     "description" TEXT;

-- AlterTable
ALTER TABLE "habitracker_app"."task_unit" ADD COLUMN     "isPredefined" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "userId" TEXT;

-- CreateTable
CREATE TABLE "habitracker_app"."notification_type" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,

    CONSTRAINT "notification_type_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "habitracker_app"."achievement_definition" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "pointsDefault" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "achievement_definition_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "habitracker_app"."reward_event" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "achievementDefinitionId" TEXT NOT NULL,
    "pointsAwarded" INTEGER NOT NULL DEFAULT 0,
    "sourceType" TEXT,
    "sourceId" TEXT,
    "title" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "reward_event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "habitracker_app"."group_member" (
    "id" TEXT NOT NULL,
    "groupId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "group_member_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "habitracker_app"."notification" (
    "id" TEXT NOT NULL,
    "receiverId" TEXT NOT NULL,
    "senderId" TEXT NOT NULL,
    "notificationTypeId" TEXT NOT NULL,
    "senderName" TEXT NOT NULL,
    "senderAvatar" TEXT,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "data" JSONB NOT NULL DEFAULT '{}',
    "isRead" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notification_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "notification_type_code_key" ON "habitracker_app"."notification_type"("code");

-- CreateIndex
CREATE UNIQUE INDEX "achievement_definition_code_key" ON "habitracker_app"."achievement_definition"("code");

-- CreateIndex
CREATE INDEX "reward_event_userId_createdAt_idx" ON "habitracker_app"."reward_event"("userId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "reward_event_achievementDefinitionId_idx" ON "habitracker_app"."reward_event"("achievementDefinitionId");

-- CreateIndex
CREATE INDEX "group_member_userId_idx" ON "habitracker_app"."group_member"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "group_member_groupId_userId_key" ON "habitracker_app"."group_member"("groupId", "userId");

-- CreateIndex
CREATE INDEX "notification_receiverId_isRead_createdAt_idx" ON "habitracker_app"."notification"("receiverId", "isRead", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "notification_notificationTypeId_idx" ON "habitracker_app"."notification"("notificationTypeId");

-- CreateIndex
CREATE INDEX "category_userId_idx" ON "habitracker_app"."category"("userId");

-- CreateIndex
CREATE INDEX "challenge_creatorId_idx" ON "habitracker_app"."challenge"("creatorId");

-- CreateIndex
CREATE INDEX "comment_postId_idx" ON "habitracker_app"."comment"("postId");

-- CreateIndex
CREATE INDEX "post_userId_createdAt_idx" ON "habitracker_app"."post"("userId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "post_groupId_idx" ON "habitracker_app"."post"("groupId");

-- CreateIndex
CREATE INDEX "post_challengeId_idx" ON "habitracker_app"."post"("challengeId");

-- CreateIndex
CREATE INDEX "task_challengeId_idx" ON "habitracker_app"."task"("challengeId");

-- CreateIndex
CREATE INDEX "task_completion_taskId_completedAt_idx" ON "habitracker_app"."task_completion"("taskId", "completedAt" DESC);

-- CreateIndex
CREATE INDEX "task_unit_userId_idx" ON "habitracker_app"."task_unit"("userId");

-- AddForeignKey
ALTER TABLE "habitracker_app"."reward_event" ADD CONSTRAINT "reward_event_userId_fkey" FOREIGN KEY ("userId") REFERENCES "habitracker_app"."habit_profile"("userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."reward_event" ADD CONSTRAINT "reward_event_achievementDefinitionId_fkey" FOREIGN KEY ("achievementDefinitionId") REFERENCES "habitracker_app"."achievement_definition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."task" ADD CONSTRAINT "task_challengeId_fkey" FOREIGN KEY ("challengeId") REFERENCES "habitracker_app"."challenge"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."post" ADD CONSTRAINT "post_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "habitracker_app"."group"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."post" ADD CONSTRAINT "post_challengeId_fkey" FOREIGN KEY ("challengeId") REFERENCES "habitracker_app"."challenge"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."challenge" ADD CONSTRAINT "challenge_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "habitracker_app"."habit_profile"("userId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."group_member" ADD CONSTRAINT "group_member_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "habitracker_app"."group"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."group_member" ADD CONSTRAINT "group_member_userId_fkey" FOREIGN KEY ("userId") REFERENCES "habitracker_app"."habit_profile"("userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."challenge_member" ADD CONSTRAINT "challenge_member_challengeId_fkey" FOREIGN KEY ("challengeId") REFERENCES "habitracker_app"."challenge"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."challenge_member" ADD CONSTRAINT "challenge_member_userId_fkey" FOREIGN KEY ("userId") REFERENCES "habitracker_app"."habit_profile"("userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."notification" ADD CONSTRAINT "notification_receiverId_fkey" FOREIGN KEY ("receiverId") REFERENCES "habitracker_app"."habit_profile"("userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."notification" ADD CONSTRAINT "notification_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "habitracker_app"."habit_profile"("userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "habitracker_app"."notification" ADD CONSTRAINT "notification_notificationTypeId_fkey" FOREIGN KEY ("notificationTypeId") REFERENCES "habitracker_app"."notification_type"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
